### ISSUE TITLE
Tpy3_StructTerm seems to be grouped at the end of the struct.

### ISSUE THREAD

**Issue by zmanian** [tendermint/go-amino#149]
Below is a test vector for SignVoteStruct generated by the snippet here: https://github.com/tendermint/kms/issues/14

The SignVote struct contains 3 sub struct. `0x04` is the typ3 for struct termination.

I would expect that we would see the `0x04` inside the the body of the serialized data instead of grouped at the end.

Based on the structs I have reviewed I have never seen a Typ3_StructTerm inside the body of the data.

This seems to me to be a bug

```
0x58, 0x6c, 0x1d, 0x3a, 0x33, 0xb, 0xa, 0x14, 0xa3, 0xb2, 0xcc, 0xdd, 0x71, 0x86, 0xf1, 0x68, 0x5f, 0x21, 0xf2, 0x48, 0x2a, 0xf4, 0xfb, 0x34, 0x46, 0xa8, 0x4b, 0x35, 0x10, 0xaa, 0xf7, 0x6, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30, 0x39, 0x20, 0x4, 0x2b, 0x9, 0x0, 0x0, 0x0, 0x0, 0x5a, 0x40, 0x69, 0xb1, 0x15, 0xd, 0xf2, 0x8e, 0x80, 0x4, 0x30, 0x1, 0x3b, 0xa, 0x4, 0x68, 0x61, 0x73, 0x68, 0x13, 0x8, 0x80, 0x89, 0x7a, 0x12, 0xa, 0x70, 0x61, 0x72, 0x74, 0x73, 0x5f, 0x68, 0x61, 0x73, 0x68,0x4, 0x4, 0x4, 0x4

```

**Comment by liamsi** [comment]
I wondered about this, too. I first had all the 
```rust 
let struct_end_postfix = typ3_to_byte(Typ3Byte::Typ3_StructTerm);
buf.put(struct_end_postfix);
``` 
after the encoding of the struct in amino_rs and moved them too the end as in `SignVoteStruct`.

**Comment by liamsi** [comment]
The code also looks as if this was happening:
https://github.com/tendermint/go-amino/blob/c7424fdd930314cc4c344b331e112dac004718ef/binary-encode.go#L350-L395

**Comment by liamsi** [comment]
If you look closely there are in fact some `0x4` in between. I don't think this is a bug. That there are 4 struct terminators at the very end makes sense in this particular example.

**Comment by zmanian** [comment]
I don't think that is true. In my rust code, I never invoked the typ3_StructTerm until the very end.

**Comment by liamsi** [comment]
I had to append `typ3_StructTerm` in between to match up with the generated golang test-vector (for `Proposal`). The example you are referring to (https://github.com/tendermint/kms/issues/14) would need to do the same if the structs weren't at the very end. Also you add `typ3_StructTerm` when you encode a timestamp: https://github.com/tendermint/amino_rs/blob/36181b32ba086b4f2cc412fc19ea88eeee45854d/src/encoding.rs#L381

**Comment by zmanian** [comment]
Any idea why we don't have a StructTerm at the end of the Address struct?

**Comment by liamsi** [comment]
Let me check. Which is the Address struct? (I don't see one in tendermint/kms#14). Are you referring to heartbeat?

**Comment by liamsi** [comment]
If you are referring to heartbeat: although the rust code looks like you are encoding a struct `ValidatorAddress`:
```rust
#[derive(PartialEq,Debug)]
pub struct ValidatorAddress(pub [u8;20]);

pub struct Heartbeat {
    validator_address: ValidatorAddress,
    validator_index: i64,
    height: i64,
    round: i64,
    sequence: i64,
    signature: Option<Signature>,
}
```
You are encoding bytes and not a struct. That's why you do not need a `StructTerm ` at the end of that. See the corresponding go code:

```golang
type Address = cmn.HexBytes

type Heartbeat struct {
	ValidatorAddress Address          `json:"validator_address"`
	ValidatorIndex   int              `json:"validator_index"`
	Height           int64            `json:"height"`
	Round            int              `json:"round"`
	Sequence         int              `json:"sequence"`
	Signature        crypto.Signature `json:"signature"`
}
```

Does this clarify your concerns?

**Comment by jaekwon** [comment]
As @Liamsi wrote, an Address is a byte-slice, which is not a struct, so they are encoded like 
 `<uvarint(length(bytes))><bytes>`.  Same is true for strings.  They don't require a struct-terminator, only structs do.

Another thing that's maybe confusing here is that there's a trailing 0x04 (the very last one) after structs, even the top-level struct implied by the context.

Structs are encoded by a list of fields (field key{number+typ3} and field value), followed by a struct-terminator 0x04.  Not all structs are encoded by a leading struct typ3.  For example, structs encoded as list elements do not start with a struct typ3 (since it is implied).  And, when you're encoding/decoding a struct directly (not as an interface) to cdc.MarshalBinary() or cdc.MarshalJSON(), the struct is implied in the context.  -- When decoding a struct as an interface, it needs to be registered & thus will start with prefix/disfix bytes.  When decoding a struct as that struct, if the struct is not registered, then decoding will assume that the first byte is the field key of the first field of the root struct.

If we're decoding a list-of-structs element, then the fact that every element is a struct is already encoded in the beginning of the list.  Instead of redundantly writing the Struct-typ3-byte before each struct, each struct's beginning is implied by the previous struct's termination.  When encoded as an embedded struct, it's provided by the field-typ3.  When encoded as an interface, it's provided by the least-significant 3 bits of the 4 prefix bytes for that concrete type.  And when encoding from a tool like `aminoscan` the context is provided by the usage of the tool.

![image](https://user-images.githubusercontent.com/53785/39887451-1f0c2872-5447-11e8-844a-1e6b2cb1484b.png)

Try yourself:
```bash
aminoscan 0b0a14a3b2ccdd7186f1685f21f2482af4fb3446a84b3510aaf70619000000000000303920042b09000000005a4069b1150df28e800430013b0a0468617368130880897a120a70617274735f6861736804040404
```

**Comment by liamsi** [comment]
Thanks chiming in and for the extensive explanation @jaekwon 👍 I wonder if we should also port aminoscan to Rust :-)

@zmanian are you OK with closing this? Or are you still concerned there is a bug? If so, could you further explain what the problem is?

**Comment by zmanian** [comment]
I think we are good!
