### ISSUE TITLE
Proposal: make amino fully compatible with proto3, except for oneof

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#156]
Aminos shining feature and motivator is the way it handles oneof.

To simplify integrations and useability, we should consider making Amino perfectly compatible with the subset of protobuf3 that does not include `oneof`. Then any structs that do not themselves contain interfaces will be perfectly proto3. If they're registered, they'll just also be prefixed with the type bytes 

This would be great for things like the Header and IAVL node structure if we could just point to structs and say "proto3". Especially since these pieces are critical in IBC. It would also dramatically simplify implementation to just be able to append prefix bytes than have to change the way structs are encoded ...

**Comment by mdyring** [comment]
Given that you guys are working towards wire compatibility with Protobuf, I would encourage the team to take 3 steps back and re-evaluate if the future work and risks Amino introduce are worth the perceived advantages?

To an outsider, the path of least resistance seem to be using Protobuf alongside a style-guide.

From the README there are two sellings points of Amino vs. Protobuf3:

- Encoding efficiency
- Protobuf `oneof` - _as implemented in Go_ - is clunky

Addressing encoding efficiency first. Developing [yet another serialization format](https://xkcd.com/927/) and expending the resources required to create a (a slightly modified) Protobuf from scratch, makes very little sense compared to the perceived reduction in size. Does the size reduction take into account that type information now needs to be stored for even the tiniest objects? (pubkey)

Even if it does, and the coding efficiency is marginally better, this is a premature optimization. A project such as Tendermint/Cosmos should focus on delivering the product and not reinvent the wheel (for each and every language that needs to be supported), which only increase the risk of not delivering on time.

According to the README, `oneof` is clunky:
"[...] Protobuf3's oneof support feels more like a (bad) encoding for C union types. For example, you can't declare a union type and re-use it in Protobuf."

The above example (of not being able to declare a "union type" and re-using it) is trivially implemented using Protobuf:

```
message TypeA
{
  uint64 some_integer = 1;
}

message TypeB
{
  bytes some_bytes = 1;
}

message ReusableUnion
{
  oneof inner
  {
    TypeA = 1;
    TypeB = 2;
  }
}

message MessageA
{
  ReusableUnion reusable_union = 1;
}

message MessageB
{
  ReusableUnion reusable_union = 1;
}
```

Also related to https://github.com/tendermint/go-amino/issues/143 and https://github.com/tendermint/tendermint/issues/1524

**Comment by gibson042** [comment]
:clap: :clap: :clap:

**Comment by jaekwon** [comment]
> Addressing encoding efficiency first. Developing yet another serialization format and expending the resources required to create a (a slightly modified) Protobuf from scratch, makes very little sense compared to the perceived reduction in size. Does the size reduction take into account that type information now needs to be stored for even the tiniest objects? (pubkey)

That's not true, you only need the disamb/prefix bytes (8/4 bytes, usually 4) for registered objects that are intended to implement an interface.  Other objects, like Vote, don't need additional type information.  And, you can still do what Proto3 does with regards to empty fields if you need to shave all the bytes.

One-of is a union type.  It is not an interface.  With an interface, anyone can implement an object under the interface.  With your example, you've forced users of MessageA.ReusableUnion to TypeA or TypeB, but that's not how interfaces work.  As an interface user, I should be able to define my own TypeC and simply use MessageA... something that can't be done with your example.

Besides the first point above, the compiled code from ReusableUnion would be a struct with fields... The goal of Amino is to reach maximum parity with the language while aiming for maximum language compatibility (there will be trade-offs).  As a Golang user I want to define and use *interfaces* and be able to serialize them.

> Even if it does, and the coding efficiency is marginally better, this is a premature optimization. A project such as Tendermint/Cosmos should focus on delivering the product and not reinvent the wheel (for each and every language that needs to be supported), which only increase the risk of not delivering on time.

It's time to finalize a few aspects of the design before we declare it final.  Here, we're discussing whether and how to make Amino more compatible with Proto3 so that in some cases we can use a restricted subset of Amino.  This makes sense in terms of concerns regarding time to delivery.

I want us to deliver the best development experience on the Cosmos SDK.  Amino makes the SDK a lot better than either with pure encoding/json, or with proto3.  I understand that this will be contentious decision, but I'm sure that I'm committed to spreading Amino.  It's already done, anyways.

**Comment by jaekwon** [comment]
Besides OneOf, here are the other things to consider:

* Embedded structs/messages - These are byte-length prefixed in Proto3.  Even if we don't make this Proto3 compatible, we can maybe avoid embedded structs.
* Time is encoded as an embedded struct.  So is BlockID
* Repeated fields besides byte-slices.  I don't see this used in the block header nor iavl nodes.
* Struct terminator for the top-level struct.  This could get more nuanced, because it's got a tail-recursive component where the tail-most embedded struct also does not need a struct-terminator.  But a simpler solution would be to just drop the top-level struct-terminator.

I'm hesitant to support optional byte-length prefixing of embedded structs in Amino, because it would require the same functionality to be implemented in all Amino libraries in order to parse Tendermint objects.  Repeated fields vs lists especially, because it's inefficient to dynamically allocate lists as they grow while decoding, and even optimized code would have to double-scan the items to efficiently allocate the list before decoding.

If I had to yield one thing, it would be struct field tag options to encode Time and embedded structs as byte-length prefixed objects for Proto3 compatibility.  But only if we don't go so far as to support Proto3's repeated fields... unless I'm misunderstanding something about Proto3.

Not sure how to do one without it becoming a slippery slope for the other.  Maybe it's sufficient to get everyone to promise here :)

**Comment by mdyring** [comment]
> I want us to deliver the best development experience on the Cosmos SDK. Amino makes the SDK a lot better than either with pure encoding/json, or with proto3. I understand that this will be contentious decision, but I'm sure that I'm committed to spreading Amino. It's already done, anyways.

During the fundraiser, and last I checked, Cosmos was dubbed "the Internet of Blockchains". The Cosmos SDK alone does not deliver on this promise, as it is inherently tied to Go and a serialization format not supported on [major languages](https://www.tiobe.com/tiobe-index/).

The promise can only be fulfilled by enabling projects developed using a variety of languages and toolchains, otherwise it is "Internet of Cosmos-SDK chains".

In summary, what I am arguing for is keeping all *public APIs* open without enforcing unnatural restrictions and costs, such as Amino support, on 3rd party developers. Specifically:
- You guys using Amino internally is fine by me. I don't necessarily agree that it is the right choice, but the Cosmos development team will carry the cost.
- Letting Amino spill into public APIs (like a [babushka API](https://github.com/tendermint/tendermint/issues/1524#issuecomment-389808591)) will be detrimental for adoption and run counter to the stated goals of the project.

Everything above this line is what really matters: Cosmos adoption.

---

Below are some further comments from a fellow developer. :-)

> That's not true, you only need the disamb/prefix bytes (8/4 bytes, usually 4) for registered objects that are intended to implement an interface. Other objects, like Vote, don't need additional type information. 

That might be the case today, but this is without supporting versioning. Unless you decide otherwise, then according to https://github.com/tendermint/go-amino/issues/143 the plan is to introducing tags to facilitate this. This will offset the space savings.

> One-of is a union type. It is not an interface. With an interface, anyone can implement an object under the interface. With your example, you've forced users of MessageA.ReusableUnion to TypeA or TypeB, but that's not how interfaces work. As an interface user, I should be able to define my own TypeC and simply use MessageA... something that can't be done with your example.

You are right that both the sender and receiver needs to know about TypeC using Proto. Amino doesn't (AFAICS) magically solve this by using interfaces: the receiver still needs to know about TypeC to decode it or things will break. 

So while it might make the developer experience nicer on Go, it doesn't introduce a solution to problems not covered today by existing tools and techniques.

Upgrades are probably best addressed by protocol level versioning as [already suggested](https://github.com/tendermint/go-amino/issues/143#issuecomment-390694680) by @amrali.

**Comment by ttmc** [comment]
To me, when I see someone creating their own new serialization format, I do a facepalm. It's such a classic error of programmer hubris. "I'm smarter than all those other guys and here's why and here's my new, better serialization format. Don't worry! It's so awesome that every other programming language will surely have an implementation in no time." Uh huh. Maybe if you're Google, Facebook or Microsoft. Everyone else should just pick one from the menu and _deal with it_.

[Comparison of Serialization Formats (Wikipedia article)](https://en.wikipedia.org/wiki/Comparison_of_data_serialization_formats)

**Comment by zmanian** [comment]
Here is my take based on my experience working with amino_rs so far.

I am strongly in favor of continuing down the amino path for internal SDK interfaces.

I haven't seen a satisfactory serialization format for distributed peer to peer systems. 

We need a self describing, reflection friendly serialization format that roughly maps to protobufs value level encoding strategy.

The IAVL tree encoding isn't really amino dependent and I support amino, protobuf and RLP encodings for a packet level encodings for IBC.

I don't think adopting protobuf will get us to supporting only 1 IBC packet encoding format. I think we will always need to support > 1 encoding format to build an internet of blockchains.

**Comment by jaekwon** [comment]
The WWW became what most people call "the internet" via a well designed set of protocols; HTTP, HTML, on top of TCP/IP.

For us for Cosmos (regardless of our design decisions for ABCI), the SDK, Amino, our Merkle tree implementations, and the generic Merkle proof system and IBC that we're developing, are our chosen primitives.  We're much more likely to win by forging ahead with these great protocols, than to spend time and commit to complexity forever by too heavily favoring protocol compatibility.

See the Peggy design for connecting zones to the Cosmos Hub, more info on that coming soon (for Ethereum, but the method applies to all blockchains, even those that don't speak Amino/Proto.

For the immediate future, I strongly believe that our strategy should be to provide cross-language compatibility via Go->XYZ integrations (there are ways for each major language). This will be the easiest way to get the logical functionality you want out of our IBC/merkle/Header blobs.  If you're OK with Proto3 requiring some opaque C++ binary to be installed in everyone's laptops, well, it's not much different than starting from Go to produce cross-platform libraries.  If it works, it will get everyone from A to B faster than any alternative.

**Comment by jaekwon** [comment]
Ok guys.  I'm over my bias.  Let me see how hard it would be to make Amino lists encode as repeated lists.  Structs are easy.

Proto embedded structs impede write performance, and its repeated-fields impede read performance.  But, I'm over it.

**Comment by jaekwon** [comment]
I'm over myself, and I'm investigating this now.  Cheers.

**Comment by jaekwon** [comment]
Making Amino more compatible with Proto would help bring more users onto Amino.  Amino2 can revisit some of our design decisions.  Sounds fine to me.  Thanks @ebuchman and @mdyring, two men more stubborn than I am.

**Comment by jaekwon** [comment]
Here's a work in progress.  This implements Proto3 style inner messages and lists (both packed for numeric lists and unpacked for strings/structs).

I think for the blockchain use-cases we're going for, in terms of performance and also in terms of codec complexity these are strictly worse designs than the original proposed Amino... but I think starting with Proto3 compatibility will be good because then we can gain more support from the existing Proto3 user-base.

https://github.com/tendermint/go-amino/pull/163

Thanks for the suggestions, @mdyring @ebuchman .

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/go-amino/issues/164.

Also I believe this is now done! Go team!
