### ISSUE TITLE
Disallow `nil` in lists (repeated fields)

### ISSUE THREAD

**Issue by liamsi** [tendermint/go-amino#212]
Different from protobuf we currently allow to encode nil in repeated fields. This causes ambiguity while decoding. For more details see:
https://github.com/tendermint/go-amino/pull/209#issuecomment-409930666

This is a simple yet bigger change as it will err on many fuzzer rounds.

**Comment by jaekwon** [comment]
A bit more nuanced because Tendermint requires this feature, e.g. in Commit where []*Vote and vote may be nil to denote absence.

This PR solves it by letting you denote a field tag `amino:"empty_elements"` which then behaves in the way you specified, otherwise the behavior is the same (e.g. what Tendermint currently expects).

https://github.com/tendermint/go-amino/pull/206

**Comment by jaekwon** [comment]
Closing because I think it's fixed, but please re-open if needed.
