### ISSUE TITLE
Why Uint16s

### ISSUE THREAD

**Issue by ebuchman** [tendermint/go-amino#57]
We have functions for writing `[]uint16` but not anything else. 

Do we need that? Maybe we can remove. 

Also, the implementation appears buggy: https://github.com/tendermint/go-wire/blob/develop/nowriter/tmdecoding/tm_decoder_pure.go#L158
 - should use `+2` and needs to slice off the first 4 bytes (the length) before reading the rest

**Comment by petabytestorage** [comment]
i think for a primitive writing interface it makes sense to provide the most generic variations. for the most generic version it is obvious to me we want a raw uint16 writer than takes an array and does not prepend the length. because without it a lot of stuff becomes impossible. whereas if we have that function available it can be easily combined with another simple primitive writer to create the length prefixed variation. so in terms of natural breakdown of the problem the non-length-prefixed variation is more fundamental and general so should be done first. so i consider this a semantic bug in the old code and a functionality gap not to have the simple array writer.  the length prefixed variation is extra and out of order in that absence.

**Comment by ebuchman** [comment]
sure, but shouldn't we also have `Uint32s` and `Int32s` and so on ? Seems a bit excessive, and we don't even use them anywhere. 

My impression would be that the lib would know how to handle slices of its native types, and we can have options for both raw encoding and length-prefixed encoding of them. 

But not sure it means we need all these special functions for arrays of everything ? Maybe I'm wrong though :)

**Comment by petabytestorage** [comment]
1. it's not obvious whether or not we use them in general and it's not clear from the code as it stood that we don't use them. even if we don't currently use them here is a case where having the full functionality available in advance is not wrong. because there's no question not having it is potentially a big performance hit and also having it clearly in one spot with good names means the cost is nearly free (in terms of conceptual complexity for other coders). So if we now introduce a new interface called UnlengthPrefixedArrayWriter and put all the array functions together there (by moving this old out of place one) we can solve many problems at once.

**Comment by petabytestorage** [comment]
2. Then introduce LengthPrefixedArrayWriter with a similar or same interface signature and we are done and clearer and more testable and easier to understand and carry.

**Comment by petabytestorage** [comment]
3. There are many tangents. We should do the most important ones first. As we increase in awareness that means we are noticing more openings yet being more discriminating by discounting those openings that are likely to be easy to fix later or have less impact.  I want clarity as the primary impact here and I wanted it last week. So in this specific case, I agree with you that we should have 8, 32, and 64 in addition to 16. We should also have x2 for uint and int.  And that code is so obvious and mechanical that I don't need to blow up this first PR (that was mostly mergeable at 250 lines) into 1500. And we really need to get into a solid flow that is why it's important to agree that this should and will be done but I hope in the proper order which would mean "whenever" in this context because the code is not yet connected and the "danger" of not doing it is almost nothing -- the first person to need it will write the loop and then it will either be copied around (sad) or properly organized. It's such an easy PR I'm sure I will feel like doing it some evening when I am tired. Then it would feel good instead of feeling bad now like it's blocking my main purpose with the larger PR involving interface improvement and renaming. I think we need to choose our battles and discussions wisely to make sure we don't waste our time and energy. I think the most impactful thing we can talk about is what was wrong and right in terms of spec and clarity at the interface level and we can rely on that clarity and testability to ferret out bugs in body code that we are not relying on.

**Comment by petabytestorage** [comment]
for me it is a no-brainer that the raw versions are clearer so carry their own weight. the length prefixed versions are confusing (poorly) named, so rightly removed and only reintroduced when somebody bothers to describe them in technical monosemous terms.

**Comment by petabytestorage** [comment]
https://github.com/tendermint/go-wire/issues/58 and https://github.com/tendermint/go-wire/issues/59

**Comment by liamsi** [comment]
> Also, the implementation appears buggy: https://github.com/tendermint/go-wire/blob/develop/nowriter/tmdecoding/tm_decoder_pure.go#L158

The linked code above doesn't exist anymore.

> sure, but shouldn't we also have Uint32s and Int32s and so on ? Seems a bit excessive, and we don't even use them anywhere.

I do not think this is stil an issue in amino. If I'm wrong, please reopen the issue @ebuchman
